spring.application.name=springbdatastore

# Configuración de Google Cloud Datastore
# Reemplaza 'TU_PROJECT_ID' con el ID real de tu proyecto en GCP
spring.cloud.gcp.project-id=springbdatastore-48220
spring.cloud.gcp.datastore.enabled=true
